server:
   port: 9200
   tomcat:
      max-swallow-size: -1
spring:
   servlet:
      multipart:
         max-file-size: -1
         max-request-size: -1
   datasource:
      url: ${DB_URL:jdbc:postgresql://localhost:5030/gamifyversedb}
      username: ${DB_USER:gamifyverseadmin}
      password: ${DB_PASS:!password!}
   jpa:
      hibernate:
         ddl-auto: none
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
   environment-type: local
   application:
      name: Gamify-API
logging:
   level:
      root: INFO